### ISSUE TITLE
Error when running test_spline test 

### ISSUE THREAD

**Issue by xukuanHIT** [pypose/pypose#269]
### 🐛 Describe the bug

An error occurred when I ran [this test](https://github.com/pypose/pypose/blob/be1bd46ea2d7dd49d903b47f370e97e6759f9b77/tests/function/test_spline.py) in my computer.
```
Traceback (most recent call last):
  File "tests/function/test_spline.py", line 93, in <module>
    spline.test_bsplilne()
  File "tests/function/test_spline.py", line 32, in test_bsplilne
    torch.testing.assert_close(poses[...,[0,-1],:].rotation(),
  File "/home/xukuan/anaconda3/envs/pypose/lib/python3.8/site-packages/torch-2.0.1-py3.8-linux-x86_64.egg/torch/testing/_comparison.py", line 1511, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 4 / 48 (8.3%)
Greatest absolute difference: 1.881717026233673 at index (1, 2, 1, 3) (up to 1e-05 allowed)
Greatest relative difference: 2.0000011044297827 at index (1, 2, 1, 2) (up to 1.3e-06 allowed)
```

### Versions

```
Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4080
Nvidia driver version: 525.116.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[conda] torch                     2.0.1                    pypi_0    pypi
```

**Comment by wang-chen** [comment]
This was fixed by #272
