### ISSUE TITLE
cumprod cuda issue

### ISSUE THREAD

**Issue by haleqiu** [pypose/pypose#73]
### Summary

cumprod cuda issue

### Steps to reproduce

```
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypose as pp
>>> dr = pp.identity_SO3(1,2)
>>> pp.cumprod(dr, dim = 1)
SO3Type LieTensor:
tensor([[[0., 0., 0., 1.],
         [0., 0., 0., 1.]]])
>>> dr = pp.identity_SO3(1,2, device="cuda:0")
>>> pp.cumprod(dr, dim = 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuheng/workspace/pypose/pypose/lietensor/lietensor.py", line 573, in __repr__
    ' %s:\n'%(self.__class__.__name__) + super().__repr__()
  File "/home/yuheng/anaconda3/lib/python3.9/site-packages/torch/_tensor.py", line 303, in __repr__
    return handle_torch_function(Tensor.__repr__, (self,), self)
  File "/home/yuheng/anaconda3/lib/python3.9/site-packages/torch/overrides.py", line 1394, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
  File "/home/yuheng/workspace/pypose/pypose/lietensor/lietensor.py", line 580, in __torch_function__
    data = torch.Tensor.__torch_function__(func, ltypes, args, kwargs)
  File "/home/yuheng/anaconda3/lib/python3.9/site-packages/torch/_tensor.py", line 1142, in __torch_function__
    ret = func(*args, **kwargs)
  File "/home/yuheng/anaconda3/lib/python3.9/site-packages/torch/_tensor.py", line 305, in __repr__
    return torch._tensor_str._str(self)
  File "/home/yuheng/anaconda3/lib/python3.9/site-packages/functorch/_src/monkey_patching.py", line 23, in _functorch_str
    return _old_str(tensor)
  File "/home/yuheng/anaconda3/lib/python3.9/site-packages/torch/_tensor_str.py", line 434, in _str
    return _str_intern(self)
  File "/home/yuheng/anaconda3/lib/python3.9/site-packages/torch/_tensor_str.py", line 409, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/yuheng/anaconda3/lib/python3.9/site-packages/torch/_tensor_str.py", line 264, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/yuheng/anaconda3/lib/python3.9/site-packages/torch/_tensor_str.py", line 100, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: CUDA error: invalid configuration argument
```

**Comment by junqiwu02** [comment]
@haleqiu Could you provide the version of pytorch and cuda you are using? I'm unable to reproduce the issue you are having.

**Comment by haleqiu** [comment]
@junqiwu02 The cuda version is 11.4, and the pytorch is the newest recommended version. 
I test the code on docker, it is fine.

This error only happen in one PC which is not available now. So I can't reproduce it in this time.
@wang-chen I suggest we can close this issue first.
